root = "."
tmp_dir = "tmp"
[build]
cmd = "go build -o ./tmp/main.exe main.go"
bin = "./tmp/main.exe"
delay = 1000 # ms
include_ext = ["go", "tpl", "tmpl", "html", "*.json"]
exclude_dir = ["public"]
exclude_regex = ["_test\\.go"]